export const CVSS31_METRIC_GUIDANCE = [
  "CVSS 3.1 base scoring describes the vulnerability as observed in its original component. Choose each metric from the real attack path and demonstrated impact, not from the vulnerability name, tool severity, exploit popularity, or desired result. Use AV, AC, PR, UI, S, C, I, and A exactly once. If the evidence cannot distinguish two values, keep the finding a lead, gather the missing observation, and calculate again instead of selecting the more severe value.",
  "AV (Attack Vector) describes how close the attacker must be to the vulnerable component. AV:N Network: the component is reachable through a network protocol and the attacker can be anywhere up to the Internet; choose it for remotely exploitable HTTP, DNS, SSH, or similar paths. AV:A Adjacent: the component is network-bound but exploitation is limited to a logically or physically adjacent network or restricted administrative domain such as a local subnet, Bluetooth segment, or secure VPN zone; choose it only when a remote Internet attacker cannot reach the path. AV:L Local: the component is not bound to the network stack and exploitation requires local read, write, or execute access, including an SSH session, or relies on another user performing the required action; choose it for a local account or local process path. AV:P Physical: the attacker must physically touch or manipulate the component, such as a device, removable interface, or cold-boot target; choose it only when physical access is required.",
  "AC (Attack Complexity) describes conditions outside the attacker's control that must be present. AC:L Low: no special preparation or external condition is needed and an attacker can expect repeatable success; ordinary technical skill or a long payload does not make it High. AC:H High: success depends on a race, a particular state, an unusual preparation, a measurable timing window, or another condition the attacker cannot reliably control; choose it only when the attack cannot be performed at will.",
  "PR (Privileges Required) describes authorization held before exploitation. PR:N None: the attacker is unauthorized and needs no account or setting access on the vulnerable component. PR:L Low: the attacker has basic user capability limited to ordinary user-owned settings/files or non-sensitive resources. PR:H High: the attacker already has significant or administrative control over the vulnerable component and can reach component-wide settings/files. Do not score privileges gained after exploitation as the precondition for PR.",
  "UI (User Interaction) describes whether someone other than the attacker must act. UI:N None: the vulnerable component can be exploited without another person's action. UI:R Required: a separate user must click, open, install, approve, or otherwise act before exploitation succeeds, such as opening a malicious document or installing an application. The attacker's own commands, requests, or clicks are not UI:R.",
  "S (Scope) describes whether exploitation crosses a security authority boundary. S:U Unchanged: the vulnerable and impacted components are governed by the same security authority; the impact stays within the same application, service authority, or security domain. S:C Changed: exploitation lets the vulnerable component affect resources governed by a different security authority, such as escaping a sandbox into the host or using one service to affect a separately managed component. Different processes, hosts, or containers alone do not make Scope Changed.",
  "C (Confidentiality) describes unauthorized disclosure in the impacted component. C:N None: no confidential information is disclosed. C:L Low: some restricted information is disclosed, but the attacker cannot choose or control the amount/kind and the loss has no direct serious consequence. C:H High: all resources in the impacted component are disclosed, or even a limited disclosure is directly serious, such as administrator credentials, private keys, or equivalent secrets. Select the highest value supported by the actual exposed data, not by the theoretical contents of a reachable endpoint.",
  "I (Integrity) describes unauthorized modification or loss of protection in the impacted component. I:N None: no data, configuration, or protection is modified. I:L Low: modification is limited or the attacker cannot control the consequence, and it has no direct serious impact. I:H High: the attacker can modify any or all protected data, bypass protection completely, or make a limited modification with a direct serious consequence. Use observed write/control capability rather than assuming code execution automatically means every impacted component has High integrity.",
  "A (Availability) describes loss of access or service in the impacted component. A:N None: no availability impact. A:L Low: performance is reduced or availability is intermittent/partial, but legitimate users retain service and there is no direct serious consequence. A:H High: the attacker can fully deny access, cause a sustained or persistent outage, or repeatedly cause a limited fault whose direct consequence is serious, such as preventing new connections or exhausting a service. A single slow request or recoverable error is not automatically High.",
  "Score severity is derived only from the calculated base score: 0.0 is info, 0.1-3.9 low, 4.0-6.9 medium, 7.0-8.9 high, and 9.0-10.0 critical. CVSS does not encode environmental urgency, asset value, exploit maturity, or business context in the base vector; preserve those as separate evidence or narrative instead of inflating a base metric. Use cvss_calculate to validate the complete vector before report_add_finding."
].join("\n");
